[profile.default]
src = 'contracts/src'
test = 'contracts/test'
out = 'contracts/out'
libs = ['contracts/lib']
solc_version = "0.8.16"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config